
real	0m8.293s
user	0m1.962s
sys	0m0.536s

real	0m2.994s
user	0m1.924s
sys	0m0.431s

real	0m7.295s
user	0m2.993s
sys	0m0.633s

real	0m4.517s
user	0m2.982s
sys	0m0.522s
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 691, in create_ppi_map_plot_offline
    field_data_padded = np.concatenate([field_data, field_data[:1, :]], axis=0)
                                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 691, in create_ppi_map_plot_offline
    field_data_padded = np.concatenate([field_data, field_data[:1, :]], axis=0)
                                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 691, in create_ppi_map_plot_offline
    field_data_padded = np.concatenate([field_data, field_data[:1, :]], axis=0)
                                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined
Traceback (most recent call last):
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 1119, in process_single_file
    fig, ax = create_ppi_map_plot_offline(radar, field_name=field_name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/cjwalden/git/halo-teamx/plot_ppi_map_halo.py", line 698, in create_ppi_map_plot_offline
    field_data_padded = field_data
                        ^^^^^^^^^^
NameError: name 'field_data' is not defined

real	0m3.813s
user	0m2.366s
sys	0m0.446s
